# 应用名称
spring:
  application:
    name: fileupload
  servlet:
    multipart:
      enabled: true
      #最大支持文件大小
      max-file-size: 1000MB
      max-request-size: 1000MB
filepath: /Users/mac/Downloads/study/JAVA/code/saveFile
# 应用服务 WEB 访问端口
server:
  port: 8080


